jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Build client
        working-directory: client
        run: npm run build
