name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature-branch
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install client
        working-directory: client
        run: npm install

      - name: Install server
        working-directory: server
        run: npm install
